replicaCount: 1

image:
  repository: oamdev/terraform-controller
  tag: 0.2.8
  pullPolicy: Always

gitImage: alpine/git:latest
busyboxImage: busybox:latest
terraformImage: oamdev/docker-terraform:1.1.5
controllerNamespace: ""

# "{\"nat\": \"true\"}"
jobNodeSelector: ""
jobBackoffLimit: ""

resources:
  limits:
    cpu: "500m"
    memory: "500Mi"
  requests:
    cpu: "250m"
    memory: "250Mi"

backend:
  namespace: vela-system

githubBlocked: "'false'"

featureGates:
  # Enable the feature of allowing to delete a configuration whose cloud resources is not fully provisioned, or error happens
  # This guarantees that the partial cloud resources will be deleted when the configuration is deleted
  # Default value is true
  AllowDeleteProvisioningResource: true
