replicaCount: 1

image:
  repository: oamdev/terraform-controller
  tag: 0.2.8
  pullPolicy: Always

gitImage: alpine/git:latest
busyboxImage: busybox:latest
terraformImage: oamdev/docker-terraform:1.1.2
jobNamespace: ""

# "{\"nat\": \"true\"}"
jobNodeSelector: ""

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

backend:
  namespace: vela-system

githubBlocked: "'false'"
