apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: aliyun-oss
spec:
  JSON: |
    {
      "resource": {
        "alicloud_oss_bucket": {
          "bucket-acl": {
            "bucket": "${var.bucket}",
            "acl": "${var.acl}"
          }
        }
      },
      "output": {
        "BUCKET_NAME": {
          "value": "${alicloud_oss_bucket.bucket-acl.bucket}.${alicloud_oss_bucket.bucket-acl.extranet_endpoint}"
        }
      },
      "variable": {
        "bucket": {
          "default": "poc"
        },
        "acl": {
          "default": "private"
        }
      }
    }

  variable:
    bucket: "vela-website"
    acl: "private"

  writeConnectionSecretToRef:
    name: oss-conn
    namespace: default


